require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ScheduledEventsController do

  # This should return the minimal set of attributes required to create a valid
  # ScheduledEvent. As you add validations to ScheduledEvent, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all scheduled_events as @scheduled_events" do
      scheduled_event = ScheduledEvent.create! valid_attributes
      get :index
      assigns(:scheduled_events).should eq([scheduled_event])
    end
  end

  describe "GET show" do
    it "assigns the requested scheduled_event as @scheduled_event" do
      scheduled_event = ScheduledEvent.create! valid_attributes
      get :show, :id => scheduled_event.id.to_s
      assigns(:scheduled_event).should eq(scheduled_event)
    end
  end

  describe "GET new" do
    it "assigns a new scheduled_event as @scheduled_event" do
      get :new
      assigns(:scheduled_event).should be_a_new(ScheduledEvent)
    end
  end

  describe "GET edit" do
    it "assigns the requested scheduled_event as @scheduled_event" do
      scheduled_event = ScheduledEvent.create! valid_attributes
      get :edit, :id => scheduled_event.id.to_s
      assigns(:scheduled_event).should eq(scheduled_event)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ScheduledEvent" do
        expect {
          post :create, :scheduled_event => valid_attributes
        }.to change(ScheduledEvent, :count).by(1)
      end

      it "assigns a newly created scheduled_event as @scheduled_event" do
        post :create, :scheduled_event => valid_attributes
        assigns(:scheduled_event).should be_a(ScheduledEvent)
        assigns(:scheduled_event).should be_persisted
      end

      it "redirects to the created scheduled_event" do
        post :create, :scheduled_event => valid_attributes
        response.should redirect_to(ScheduledEvent.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved scheduled_event as @scheduled_event" do
        # Trigger the behavior that occurs when invalid params are submitted
        ScheduledEvent.any_instance.stub(:save).and_return(false)
        post :create, :scheduled_event => {}
        assigns(:scheduled_event).should be_a_new(ScheduledEvent)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ScheduledEvent.any_instance.stub(:save).and_return(false)
        post :create, :scheduled_event => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested scheduled_event" do
        scheduled_event = ScheduledEvent.create! valid_attributes
        # Assuming there are no other scheduled_events in the database, this
        # specifies that the ScheduledEvent created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ScheduledEvent.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => scheduled_event.id, :scheduled_event => {'these' => 'params'}
      end

      it "assigns the requested scheduled_event as @scheduled_event" do
        scheduled_event = ScheduledEvent.create! valid_attributes
        put :update, :id => scheduled_event.id, :scheduled_event => valid_attributes
        assigns(:scheduled_event).should eq(scheduled_event)
      end

      it "redirects to the scheduled_event" do
        scheduled_event = ScheduledEvent.create! valid_attributes
        put :update, :id => scheduled_event.id, :scheduled_event => valid_attributes
        response.should redirect_to(scheduled_event)
      end
    end

    describe "with invalid params" do
      it "assigns the scheduled_event as @scheduled_event" do
        scheduled_event = ScheduledEvent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ScheduledEvent.any_instance.stub(:save).and_return(false)
        put :update, :id => scheduled_event.id.to_s, :scheduled_event => {}
        assigns(:scheduled_event).should eq(scheduled_event)
      end

      it "re-renders the 'edit' template" do
        scheduled_event = ScheduledEvent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ScheduledEvent.any_instance.stub(:save).and_return(false)
        put :update, :id => scheduled_event.id.to_s, :scheduled_event => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested scheduled_event" do
      scheduled_event = ScheduledEvent.create! valid_attributes
      expect {
        delete :destroy, :id => scheduled_event.id.to_s
      }.to change(ScheduledEvent, :count).by(-1)
    end

    it "redirects to the scheduled_events list" do
      scheduled_event = ScheduledEvent.create! valid_attributes
      delete :destroy, :id => scheduled_event.id.to_s
      response.should redirect_to(scheduled_events_url)
    end
  end

end
